name: Building Blocks

on:
  workflow_dispatch:

jobs:
  hello:
    runs-on: ubuntu-latest

    steps:
      - name: Say Hello
        run: echo "Hello, World!"

      - name: Show Date
        run: date

      - name: Show Current Directory
        run: pwd

  goodbye:
    needs: hello
    runs-on: ubuntu-latest

    steps:
      - name: Say Goodbye
        run: echo "Goodbye, World!"